import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ChatSidebar from "@/components/chat-sidebar";
import { AuthProvider } from "@/hooks/useAuth";
import { Toaster } from "@/components/sooner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Memesh chat ai multi model",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="theme-pink"
            enableSystem
            disableTransitionOnChange
        >   
            <AuthProvider>
                <div className="min-h-screen flex">
                    <ChatSideBar />
                    {children}
                </div>
                <Toaster />
            </AuthProvider>
        </ThemeProvider>    
      </body>
    </html>
  );
}
